<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UthandoTestimonial\Module'                  => __DIR__ . '/Module.php',
  'UthandoTestimonial\Controller\Testimonial'  => __DIR__ . '/src/UthandoTestimonial/Controller/Testimonial.php',
  'UthandoTestimonial\Form\Testimonial'        => __DIR__ . '/src/UthandoTestimonial/Form/Testimonial.php',
  'UthandoTestimonial\Hydrator\Testimonial'    => __DIR__ . '/src/UthandoTestimonial/Hydrator/Testimonial.php',
  'UthandoTestimonial\InputFilter\Testimonial' => __DIR__ . '/src/UthandoTestimonial/InputFilter/Testimonial.php',
  'UthandoTestimonial\Mapper\Testimonial'      => __DIR__ . '/src/UthandoTestimonial/Mapper/Testimonial.php',
  'UthandoTestimonial\Model\Testimonial'       => __DIR__ . '/src/UthandoTestimonial/Model/Testimonial.php',
  'UthandoTestimonial\Service\Testimonial'     => __DIR__ . '/src/UthandoTestimonial/Service/Testimonial.php',
);
