<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-testimonial/testimonial/add'              => __DIR__ . '/view/uthando-testimonial/testimonial/add.phtml',
    'uthando-testimonial/testimonial/edit'             => __DIR__ . '/view/uthando-testimonial/testimonial/edit.phtml',
    'uthando-testimonial/testimonial/index'            => __DIR__ . '/view/uthando-testimonial/testimonial/index.phtml',
    'uthando-testimonial/testimonial/list'             => __DIR__ . '/view/uthando-testimonial/testimonial/list.phtml',
    'uthando-testimonial/testimonial/testimonial-form' => __DIR__ . '/view/uthando-testimonial/testimonial/testimonial-form.phtml',
    'uthando-testimonial/testimonial/view'             => __DIR__ . '/view/uthando-testimonial/testimonial/view.phtml',
);
