<?php $this->headTitle('Add Testimonial') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Testimonial');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-testimonial" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/testimonial');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php

$this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-testimonial',
    'action' => $this->url('admin/testimonial/edit', [
        'action' => 'add',
    ]),
]);

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Testimonial');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

<?php $this->textEditor()->summernote();?>
<?php $this->fileManager()->uploadButton('testimonial-image', 'testimonial-image-button');?>
