<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="testimonialId">Testimonial Id</th>
                <th data-field="company">Company</th>
                <th data-field="dateCreated">Date Created</th>
                <th data-field="dateModified">Date Modified</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoTestimonial\Model\Testimonial */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getTestimonialId()); ?></td>
                    <td><?=$this->escapeHtml($row->getCompany()); ?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'testimonialId',
                            'id'		=> $row->getTestimonialId(),
                            'tableName'	=> 'article',
                            'route'		=> 'admin/testimonial/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/testimonial/page']
    ); ?>

<?php else: ?>
    <h4>There are no testimonials yet.</h4>
<?php endif; ?>