<?php
echo $this->headScript()
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/innovaeditor.js'))
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/jquery.innovaeditor.js'))
    ->appendFile('//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js')
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/common/webfont.js'));

$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->testimonialId)) $routeArray['id'] = $this->testimonialId;
?>
<div class="row">
    <form class="col-md-12 form form-horizontal" method="post" action="<?=$this->url('admin/testimonial/edit',
        $routeArray) ?>">
        <fieldset>
        <legend><?=ucwords($this->formAction); ?> Testimonial Form:</legend>
        <div class="row">
            <div class="col-sm-6">
                <fieldset>
           	        <legend>Testimonial Details</legend>
                    <div class="form-group<?php if ($form->get('name')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="name"><?=$form->get('name')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('name')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('name'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    <div class="form-group<?php if ($form->get('image')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="image"><?=$form->get('image')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('image')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('image'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    
                     <div class="form-group<?php if ($form->get('location')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="location"><?=$form->get('location')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('location')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('location'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    
                     <div class="form-group<?php if ($form->get('company')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="company"><?=$form->get('company')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('company')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('company'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>

                    <div class="form-group<?php if ($form->get('website')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="website"><?=$form->get('website')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('website')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('website'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>

                    <div class="form-group<?php if ($form->get('sector')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="sector"><?=$form->get('sector')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('sector')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('sector'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                </fieldset>
           	</div>

            <div class="col-md-6">
                <fieldset>
                    <legend>HTML Content</legend>
                    <?=$this->formElement($form->get('text')->setAttribute('class', 'form-control')); ?>
                </fieldset>
            </div>
        </div>
                
        <?=$this->formElement($form->get('testimonialId')); ?>

        <input type="hidden" name="action" value="<?=$this->formAction; ?>">
        
        <div class="clearfix">&nbsp;</div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/testimonial', array(
                        'action' => 'list',
                    )) ?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#testimonial-content-textarea').liveEdit({
            height: '325px',
            css: [
                '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css',
                '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css',
                '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css'
            ] /* Apply bootstrap css into the editing area */ ,
            groups: [
                ["group1", "", ["Bold", "Italic", "Underline", "ForeColor", "RemoveFormat"]],
                ["group2", "", ["Bullets", "Numbering", "Indent", "Outdent"]],
                ["group3", "", ["Paragraph", "FontSize", "FontDialog", "TextDialog"]],
                ["group4", "", ["LinkDialog", "ImageDialog", "TableDialog", "Emoticons", "Snippets"]],
                ["group5", "", ["Undo", "Redo", "FullScreen", "SourceDialog"]]
            ] /* Toolbar configuration */ ,
            fileBrowser: '<?=$this->basePath('/admin/asset-manager')?>'
        });
        $('#testimonial-content-textarea').data('liveEdit').startedit(); /* Run the Editor */
    });
</script>

